services:
  mysql:
    image: mysql:8.4.4
    container_name: nestjs_base_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nestjs_base_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: nestjs_base_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - nestjs_base_network

  postgres:
    image: postgres:13.20
    container_name: nestjs_base_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
   image: mongo:7.0
   container_name: nestjs_base_mongo
   restart: unless-stopped
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: root
   ports:
     - "27017:27017"
   volumes:
     - mongo_data:/data/db

  redis:
    image: redis:7.2.4
    container_name: nestjs_base_redis
    restart: unless-stopped
    environment:
      #- REDIS_USER=default mặc định nó là user default
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "admin", "--appendonly", "yes" ]
    networks:
      - nestjs_base_network

volumes:
  mysql_data:
  mongo_data:
  postgres_data:
  redis_data:
networks:
  nestjs_base_network:
    driver: bridge
