services:
  db:
    image: mysql:8.4.4
    container_name: tuvi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306np:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tuvi_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: tuvi_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - tuvi_network


  redis:
    image: redis:7.2.4
    container_name: tuvi_redis
    restart: unless-stopped
    environment:
      #- REDIS_USER=default mặc định nó là user default
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "admin", "--appendonly", "yes" ]
    networks:
      - tuvi_network

volumes:
  mysql_data:
  redis_data:
networks:
  tuvi_network:
    driver: bridge
