app:
  name: ${APP_NAME}
  port: ${PORT}

database:
  mysql:
    type: 'mysql'
    host: ${DB_HOST}
    port: ${DB_PORT}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}
    entities:
      - 'dist/**/mysql/**/*.entity{.ts,.js}'
    synchronize: false
    logging: true
  postgresql:
    type: 'postgres'
    host: ${DB_POSTGRESQL_HOST}
    port: ${DB_POSTGRESQL_PORT}
    username: ${DB_POSTGRESQL_USER}
    password: ${DB_POSTGRESQL_PASSWORD}
    database: ${DB_POSTGRESQL_NAME}
    entities:
      - 'dist/**/postgresql/**/*.entity{.ts,.js}'
    synchronize: false
    logging: true
jwt:
  access:
    secret: ${ACCESS_TOKEN_SECRET}
    expiry: ${ACCESS_TOKEN_EXPIRY}
  refresh:
    secret: ${REFRESH_TOKEN_SECRET}
    expiry: ${REFRESH_TOKEN_EXPIRY}
